spring.application.name=refugio
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jbc:mysql://oraclepr.uco.es:3306/i42acsad
spring.datasource.username=i42acsad
spring.datasource.password=pwgatos
